---
# Ansible playbook for standard installations and commands.
- hosts: all
  become: true
  tasks:
   - name: installing and updating repos
     apt:
       update_cache: yes
       state: present

   - name: ensure ntp is installed
     apt:
       name: ntp
       state: present

   - name: ensure ntp is running 
     service:
       name: ntp
       state: started
       enabled: yes
