---
- hosts: all
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always


- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml



- name: include env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always
- name: import database file
  import_playbook: ../static-assignments/db.yml 

- name: import webservers file
  import_playbook: ../static-assignments/webservers.yml 

- name: import loadbalancers assignment
  import_playbook: ../static-assignments/lb.yml
  when: load_balancer_is_required


- name: Loadbalancers assignment
  hosts: lb
    - import_playbook: ../static-assignments/lb.yml
    when: load_balancer_is_required 